In [2]:
import pandas as pd

nutrition_df = pd.read_csv('dataset/nutrition.csv')

In [3]:
nutrition_df.head()

,id,calories,proteins,fat,carbohydrate,name,image
0,1,280.0,9.2,28.4,0.0,Abon,https://img-cdn.medkomtek.com/PbrY9X3ignQ8sVuj...
1,2,513.0,23.7,37.0,21.3,Abon haruwan,https://img-global.cpcdn.com/recipes/cbf330fbd...
2,3,0.0,0.0,0.2,0.0,Agar-agar,https://res.cloudinary.com/dk0z4ums3/image/upl...
3,4,45.0,1.1,0.4,10.8,Akar tonjong segar,https://images.tokopedia.net/img/cache/200-squ...
4,5,37.0,4.4,0.5,3.8,Aletoge segar,https://nilaigizi.com/assets/images/produk/pro...

In [4]:
nutrition_df.describe()

                id     calories     proteins          fat  carbohydrate
count  1346.000000  1346.000000  1346.000000  1346.000000   1346.000000
mean    673.500000   203.217385    10.001189     7.584027     25.390193
std     388.701042   163.075430    11.847980    13.733063     32.193054
min       1.000000     0.000000     0.000000     0.000000      0.000000
25%     337.250000    75.000000     1.800000     0.500000      4.525000
50%     673.500000   146.000000     5.000000     2.000000     13.300000
75%    1009.750000   333.750000    15.000000     8.275000     37.575000
max    1346.000000   940.000000    83.000000   100.000000    647.000000